import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import StoreProvider from './StoreProvider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import SideBar from '#/component/general/SideBar'
import { isAuthenticated } from '#/utils/actions'
import Login from '#/component/login/login'

const inter = DM_Sans({
  subsets: ['latin'],
  weight: '500',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const isLogged = await isAuthenticated()

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <StoreProvider>
       
          <ToastContainer />
            {isLogged ? <SideBar>{children}</SideBar> : <Login />}
        </StoreProvider>
      </body>
    </html>
  )
}
